### ISSUE TITLE
[Other] Please host it on Netlify or Vercel

### ISSUE THREAD

**Issue by abhirajadhikary06** [Rakesh9100/Eventica#12]
### What would you like to share?

@Rakesh9100 It would be nice to see this platform deployed online.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Eventica/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Eventica/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
This project is already deployed on Netlify, go through the repo description or Readme and you will find every detail @abhirajadhikary06

**Comment by abhirajadhikary06** [comment]
Ohh yes...Sorry for overlooking. Though this was not a valid issue 😅.

Can you just attach the same like below the project description in GitHub.

**Comment by Rakesh9100** [comment]
Attached now, please check @abhirajadhikary06

**Comment by Rakesh9100** [comment]
Attached now @abhirajadhikary06

**Comment by abhirajadhikary06** [comment]
> Attached now @abhirajadhikary06

**Comment by abhirajadhikary06** [comment]
@Rakesh9100 do you feel that this project can be further worked upon to make this an open source event booking platform ??
