### ISSUE TITLE
[Bug] Fix scrolling issue preventing navigation between sections

### ISSUE THREAD

**Issue by sammy0318** [Rakesh9100/Eventica#14]
### Description

On the website, users cannot scroll to navigate between sections (e.g., "About Us," "Upcoming Events"). These sections are only accessible via the navigation bar links, which hinders the user experience.

![Screenshot (847)](https://github.com/user-attachments/assets/36ad90b3-2d53-4b26-afda-900f15364509)

Checklist
 I have checked the existing issues.
 I follow Contributing Guidelines of this project.
 I am a KWOC'24 contributor.
Code of Conduct
 I agree to follow this project's "Code of Conduct".

**Comment by abhirajadhikary06** [comment]
@sammy0318 It is working fine, o issues. Check for errors in your browser on your side.
Thank you!

**Comment by Rakesh9100** [comment]
Which bug exactly are you trying to convey, specify in detail @sammy0318

**Comment by sammy0318** [comment]
> Which bug exactly are you trying to convey, specify in detail @sammy0318

Issue: Users cannot navigate between different sections of the webpage by simply scrolling. Instead, they must rely on the navigation bar (navbar) links.

Fix: Align all sections of the webpage vertically, one after another, to enable seamless navigation by scrolling. This will improve the user experience and provide a more intuitive interface.

**Comment by Rakesh9100** [comment]
There is no need for navigation through scrolling, as the About Us section will move much down when upcoming events are populated, so the navigation bar is fine, and easy to access any section @sammy0318
