### ISSUE TITLE
[Style] Enhance the send message button

### ISSUE THREAD

**Issue by ShreyashSri** [Rakesh9100/Eventica#15]
### Description

The Send Message button on the Contact Us page is not following the website theme on changing the colour. I would like to fix this issue

### Screenshots

![Screenshot 2024-12-15 164349](https://github.com/user-attachments/assets/a6091bc2-6641-4b77-9841-51302f7a2f09)
![Screenshot 2024-12-15 164416](https://github.com/user-attachments/assets/b4cc9db8-cee3-4f90-bb63-0eca44f388f6)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Eventica/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Eventica/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @ShreyashSri
