### ISSUE TITLE
[Style] Make event cards clickable in past events section

### ISSUE THREAD

**Issue by Astha86** [Rakesh9100/Eventica#16]
### What's the style idea?

I think in the past events section, not only the view details button but also clicking the event card should open a desired webpage.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Eventica/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Eventica/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Why do you think so, we already have the specific View details button @Astha86

**Comment by Astha86** [comment]
It will enhance user experience.

**Comment by Rakesh9100** [comment]
Okay, go ahead @Astha86
