### ISSUE TITLE
[Style] Enhance the website design and user experience

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/Eventica#2]
### What's the style idea?

Enhance the website's user interface by improving its design, layout, and overall user experience for better aesthetics and usability.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Eventica/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Eventica/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Atharvverma1234** [comment]
Hello Sir, I would like to work on this issue. Please assign it to me. Thank you

**Comment by Rakesh9100** [comment]
Do you have any idea, please brief with the help of supporting screenshots or thoughts @Atharvverma1234

**Comment by wildcraft958** [comment]
The event section cards need to be changed first. Their design is too simple, and for some events, there is no clear distinction between the card and the background.
Also, adding a hover effect for nav links would look good like one cyan color underlines fade-in fade-out effect.
There is no uniform color palette used and most things are white background which can be changed after deciding on good colors.

**Comment by Rakesh9100** [comment]
Okay, go ahead @wildcraft958

**Comment by Rakesh9100** [comment]
Provide your PR @wildcraft958

**Comment by wildcraft958** [comment]
Please lend me some  extra time i had some unavoidable  situation  due to which i wasnt able to work i will complete is asap

**Comment by Rakesh9100** [comment]
Okay @wildcraft958

**Comment by wildcraft958** [comment]
![Screenshot from 2024-12-22 19-36-39](https://github.com/user-attachments/assets/1dad2550-8fea-430e-800f-9ca50c8909af)
![Screenshot from 2024-12-22 20-25-32](https://github.com/user-attachments/assets/e58225b2-ace9-4ff3-bba9-9b4a979fb35b)
![Screenshot from 2024-12-22 20-25-36](https://github.com/user-attachments/assets/cab6ae63-956a-455d-b079-bb2691238871)
changes that i had in mind, I have made open for review
