### ISSUE TITLE
[Style] Enhance the Footer UI

### ISSUE THREAD

**Issue by pragna7** [Rakesh9100/Eventica#27]
### Description

I noticed the footer is missing on your website. I would like to contribute by adding a professional footer to enhance the site's appearance and usability.

### Screenshots

![Screenshot 2024-12-28 211109](https://github.com/user-attachments/assets/45be99c2-d2e4-49c5-af09-280e154f4ac0)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Eventica/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Eventica/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Issue 8 is already opened for the same, you can comment on that if you want to work @pragna7
