### ISSUE TITLE
[Feature] Add Scroll to top button

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/Eventica#3]
### Description

Implement a Scroll to Top button that appears when the user scrolls down the page. Clicking the button should smoothly scroll the page back to the top, enhancing navigation and user experience.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Eventica/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Eventica/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Atharvverma1234** [comment]
Hi, I would like to work on this issue. Please assign it to me. Thank you

**Comment by Rakesh9100** [comment]
Go ahead @R2-STAR
