### ISSUE TITLE
[Style] Enhance the contact form field interactions

### ISSUE THREAD

**Issue by neeru24** [Rakesh9100/Eventica#31]
### Description

I want to improve the user experience for the "Contact Us" form by adding a hover effect on the input fields. When a user hovers over any field, it should scale up slightly and highlight, making it easier for the user to identify the active fields. This will provide a more interactive and visually appealing form.

**Expected Outcome:**

- On hovering over any input field, the field should scale up (e.g., by 1.1x) and change the background or border color to make it stand out.
- The effect should be smooth and subtle for a better user experience.

### Screenshots

![image](https://github.com/user-attachments/assets/07ec405e-9165-49b5-af88-28142e447de6)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Eventica/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Eventica/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @neeru24
