### ISSUE TITLE
[Bug] Fix the navigation bar logo

### ISSUE THREAD

**Issue by sammy0318** [Rakesh9100/Eventica#9]
### Description

The navigation bar does not represent the correct logo due to some code issue

### Screenshots

![Screenshot (840)](https://github.com/user-attachments/assets/85b10147-414c-4ebc-be67-be6531529a50)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Eventica/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Eventica/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by wildcraft958** [comment]
Can you assign me?
